### ISSUE TITLE
Usage of Lychee API

### ISSUE THREAD

**Issue by koellcode** [GustavePate/lycheesync#25]
One question or Improvement: Why you gain direct access to Database and Folders and Stuff? Could you not use the Lychee HTTP Api? They have Interfaces for createAlbum and addPhotoToAlbum and stuff. The sync tool could be much leaner and better to maintain. And you only depend on their web API

**Comment by GustavePate** [comment]
Because DB + folder organisation is simple to reverse engineer
Because at the time when I needed lycheesync the http api was not really in place.
An most important, Because the lychee http api is not intended to be public, so lychee can break it whenever it need/wants to.
As a consequence update Lychee and lycheesync is not working anymore (unless I synchronize my release with lychee's -> hard work)

Breaking change can happen, with file/db too but lychee's evolution is more on the front end than the back end. In the last year,  only one breaking change happened on the db (new mandatory field).

However, if I had start the project today, I would have provided a switch to use lychee api.
