### ISSUE TITLE
os.lchown throwing errors

### ISSUE THREAD

**Issue by Enoch247** [GustavePate/lycheesync#28]
I get the following failure when I try to use lycheesync with Lychee 3.0.1. I can't seem find any reason for lycheesync to fail. Running as myself without the "sudo -u www-data" has the same result.

**josh@host:lycheesync$ sudo -u www-data ./main.py /tmp/foo/ /var/www/intranet/Lychee/ conf.json**
addFileToAlbum <type 'exceptions.Exception'>
Traceback (most recent call last):
  File "/tmp/lycheesync/lycheesyncer.py", line 150, in addFileToAlbum
    os.lchown(photo.destfullpath, self.conf['uid'], self.conf['gid'])
OSError: [Errno 1] Operation not permitted: '/var/www/intranet/Lychee/uploads/big/5eee394ebfc4e4e30aaf9387857a9b73.jpg'
addFileToAlbum <type 'exceptions.Exception'>
Traceback (most recent call last):
  File "/tmp/lycheesync/lycheesyncer.py", line 150, in addFileToAlbum
    os.lchown(photo.destfullpath, self.conf['uid'], self.conf['gid'])
OSError: [Errno 1] Operation not permitted: '/var/www/intranet/Lychee/uploads/big/1ecc40f4bcf81667eb7a69bbd90532ac.jpg'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Directory scanned: /tmp/foo/
Created albums:  0
ERROR: 0 photos imported on 2 discovered
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**the uploads/big folder is as follows:**
**josh@host:lycheesync$ ll /var/www/intranet/Lychee/uploads/big/**
total 932
-rwxr-xr-x 1 www-data www-data 469101 May 26 17:33 1ecc40f4bcf81667eb7a69bbd90532ac.jpg*
-rwxr-xr-x 1 www-data www-data 479986 May 26 17:33 5eee394ebfc4e4e30aaf9387857a9b73.jpg*
-rw-rw-r-- 1 josh     josh          0 Feb 22 21:12 index.html

**Comment by GustavePate** [comment]
Hi Enoch247,

#### Short Answer

I don't think it's a problem with lycheesync. 
I thnik that the user you launch lycheesync with has not the permission to change file permissions in 

       /var/www/intranet/Lychee/uploads/big/

#### Long answer

Lycheesync take the lycheepath you give to the commandline in your case:

        /var/www/intranet/Lychee/

It read its owner and group and then try to update photos ownership using this owner/group  pair

You can execute this command to know what user/group lycheesync is trying to set

     ls -l  /var/www/intranet/ | grep 'Lychee'

Note the owner / group of this directory
And then, as the user who launch lycheesync execute:

    chown the_previous_user:the_previous_group /var/www/intranet/Lychee/uploads/big/1ecc40f4bcf81667eb7a69bbd90532ac.jpg

It should give you an error too. 

Knowing that, you just have to fix your permission to give lycheesync user, the right to change permissions on files in the directory 

    /var/www/intranet/Lychee/uploads/big/

Let me know if that fixes your problem.

Thanks

**Comment by Enoch247** [comment]
Ahh, I see my problem. My entire Lychee folder is owned by "Josh" and write access is granted to Lychee via group permissions to only the folders with Lychee requires. I do this with all web apps to prevent the potential that a breached system could then re-write its code to do more bad things.

I think the call to chown will be problematic for any user that does not run lycheesync as root or as the same user which owns the Lychee/uploads/big folder (in which case the owner would not change). This is because the only user which can successfully transfer ownership of a file is root, and the second case of chown-ing a file to yourself is kinda pointless.

I think it would be better to just let users worry about file permissions outside of lycheesync. Since it will be impossible to anticipate any given setup. It would be entirely plausible for some users to just run lycheesync as a user having read-only access to their pictures, and just use sticky bits in the Lychee/uploads folder to give write access to Lychee. Other users may run lycheesync with the same uid/gid as Lychee is run with.

**Comment by GustavePate** [comment]
Ok, I see your point.

The whole point with the chown is to be fool proof. 
Lots of users don't have your skills with unix permissions ;) and I run in a couple of support issues where people didn't thought about the fact that their source photos must have the correct permission to allow their web server to display the photos once transfered in Lychee.

So this functionality is clearly usefull: it saves me support issues ;)

So, if I understand correctly what you said, If I chown imported photos to the user/group who owns Lychee/uploads/big (instead of Lychee) I solve your problem AND I don't recreate new ones for me.

**Comment by GustavePate** [comment]
As I dig deeper in the issue I see more potential corner cases.

Allow me to correct you:
> and the second case of chown-ing a file to yourself is kinda pointless.

This is the whole interest of the chown here, people are copying file to Lychee that are not visible by www-data (or any other webserver user) so I chown/chgrp them. (I'd rather only chgrp them by the way).

In fact, because I can only chown (or grp) my own files, I will use the group of the Lychee/uploads/big directory and will change 'chown + chgrp' to 'chgrp' on files.

Plus, problems in chgrp will cause warnings,  not errors

**Comment by GustavePate** [comment]
ok, working on a big refactor of lycheesync today I ran into your problem.
Impossible to even chgrp file I own to www-data on my local computer.
At the same time it's working flawlessly on my server.

After being stuck a good hour, I discovered that my server user is member of the www-data group, so he can chgrp to www-data...

It's not a default setup, so you are right I deactivate the chown functionnality.

Have to replace this with a good explanation in the Readme.
