### ISSUE TITLE
Use photos in their original location

### ISSUE THREAD

**Issue by Kernald** [GustavePate/lycheesync#31]
Instead of duplicating every picture in Lychee's folder, it would be great to generate thumbnails, then use the original file for the `big` version.

**Comment by GustavePate** [comment]
Hi, 

There's an **undocumented** (I will take care of this) `-l` command line switch that makes symbolic links instead of copying the files.
However, make sure that your webserver user has the permission to read your original files.

Regards,

**TODO:** document the command line switch in the README.md

**Comment by electerious** [comment]
@GustavePate Awesome! Thanks for developing the script. It's helpful for a lot of users :)

**Comment by GustavePate** [comment]
Finally documented ;) 
And Thanks @electerious  !
