### ISSUE TITLE
getting the script running

### ISSUE THREAD

**Issue by Segdon** [GustavePate/lycheesync#46]
Hello,

i got the plugin running in a test setting, but now setting it up 'for real' i can't get it to work. The verbose message:

INFO album list in db: {}
("WARN: file at srcdir root won't be added to lychee, please move them in a subfolder", '/var/www/html/owncloud/data/nostro/files/Photos/Albums/big_dbfb9ccaaa1c2959c95fc3e0df565907b18dc207.jpg')
INFO min max album id: None to None
Traceback (most recent call last):
  File "main.py", line 132, in <module>
    main(conf_data)
  File "main.py", line 19, in main
    s.sync()
  File "/var/www/html/nostrolychee/plugins/lycheesync/lycheesyncer.py", line 381, in sync
    self.reorderalbumids(albums)
  File "/var/www/html/nostrolychee/plugins/lycheesync/lycheesyncer.py", line 237, in reorderalbumids
    newid = max + 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

Do i forget to adjust some value?
Sorry if this is a stupid question.

**Comment by GustavePate** [comment]
Ok, I just commit something to avoid the corner case you stumble uppon.
If you update your lycheesync copy It will work.

However, It's not suppose to happen, I run in the same code as you are and have no problem.
What version of python do you use ? I should be 2.7
What mysqldriver have you install ?

There are 2 compatible drivers in the wild that don't behave the same.

I think you installed mysqlclient:

     sudo pip install mysqlclient

Instead of MySQLDb

     sudo pip install MySQL-python

Note for mysqelf: I should add protection that prevent lycheesync from running with the wrong driver...

**Comment by GustavePate** [comment]
won't be a pb anymore in next release: pymysql for everyone ;)
